name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo’yu çek
      - uses: actions/checkout@v3

      # 2️⃣ Python kurulumu
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ PyPI paketlerini yükle
      - name: Install PyPI dependencies
        run: |
          pip install --upgrade pip
          pip install faiss-cpu==1.7.4
          pip install -r requirements.txt --no-deps

      # 4️⃣ Testleri çalıştır
      - name: Run tests
        run: pytest --disable-warnings -v

