name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo’yu çek
      - uses: actions/checkout@v3

      # 2️⃣ Python kurulumu
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ PyPI bağımlılıklarını yükle
      - name: Install PyPI dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-deps

      # 4️⃣ Local modülleri yükle
      - name: Install local modules
        run: |
          pip install ./dp ./nlp ./learning ./main ./rate_limiter ./utils 
./schemas ./config ./database ./embedding ./fine_tuning

      # 5️⃣ Testleri çalıştır
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -v

